### ISSUE TITLE
error on cis_reports.py

### ISSUE THREAD

**Issue by ortiz-kuakside** [oracle-quickstart/oci-cis-landingzone-quickstart#6]
hi all 
we launched the script in our tenancy  and gave us this error

Processing Network Security Lists...
Processing Network Security Groups...
Processing Network Subnets...
Processing Tag Defaults..
Traceback (most recent call last):
  File "cis_reports.py", line 1500, in <module>
    execute_report()
  File "cis_reports.py", line 1493, in execute_report
    report.report_generate_cis_report()
  File "cis_reports.py", line 1238, in report_generate_cis_report
    self.__report_analyze_tenancy_data()
  File "cis_reports.py", line 1107, in __report_analyze_tenancy_data
    if irule['tcp_options'].destination_port_range.min == 22 and irule['tcp_options'].destination_port_range.max == 22:
AttributeError: 'NoneType' object has no attribute 'min'

thanks

**Comment by andrecorreaneto** [comment]
Hi Ortiz, thanks for filing this.
The issue is due to an ingress rule with wide open access from 0.0.0.0/0, as it does not have a specific destination port, thus allowing access to all ports. Make sure you don't have them in your tenancy.
We are now capturing such an issue and temporarily reporting under CIS Benchmark item 2.5, as there's still no specific rule for such configuration scenario. Please, pull the repo and let us know if the fix is effective.
Andre.
